# Generated by Django 4.0.4 on 2022-08-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0002_rename_suject_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
