# Generated by Django 4.0.4 on 2022-08-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0003_rename_name_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='help',
        ),
    ]
