# Generated by Django 4.0.4 on 2022-08-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0006_alter_help_email_alter_help_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='contact',
        ),
    ]
