# Generated by Django 4.0.4 on 2022-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0008_rename_contact_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=30)),
                ('drop_location', models.CharField(max_length=30)),
                ('pickup_date', models.CharField(max_length=30)),
                ('pickup_time', models.CharField(max_length=30)),
                ('drop_date', models.CharField(max_length=30)),
                ('drop_time', models.CharField(max_length=30)),
                ('car_name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('total_driven', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=30)),
                ('dl_number', models.CharField(max_length=30)),
                ('aadhar_image', models.ImageField(upload_to='aadharImg')),
                ('dl_image', models.ImageField(upload_to='DLImg')),
            ],
        ),
    ]
