# Generated by Django 4.0.4 on 2022-08-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0009_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact_u',
        ),
    ]
