# Generated by Django 4.0.4 on 2022-08-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0010_rename_contact_us_contact_u'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookyourcar',
        ),
    ]
