# Generated by Django 4.0.4 on 2022-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0011_rename_booking_bookyourcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookyourcar',
            name='aadhar_image',
            field=models.ImageField(null=True, upload_to='aadharImg'),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='aadhar_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='car_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='dl_image',
            field=models.ImageField(null=True, upload_to='DLImg'),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='dl_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='drop_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='drop_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='drop_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='pickup_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='pickup_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='pickup_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='total_driven',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookyourcar',
            name='transmission',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
