# Generated by Django 4.0.4 on 2022-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0012_alter_bookyourcar_aadhar_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('service_type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('special_request', models.TextField(null=True)),
            ],
        ),
    ]
