# Generated by Django 4.0.4 on 2022-08-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0014_alter_service_booking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookyourcar',
            new_name='car_Booking',
        ),
    ]
