# Generated by Django 4.0.4 on 2022-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0015_rename_bookyourcar_car_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_booking',
            name='aadhar_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='car_booking',
            name='dl_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
