# Generated by Django 4.0.4 on 2022-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0016_alter_car_booking_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_booking',
            name='aadhar_image',
            field=models.ImageField(blank='true', default='', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='car_booking',
            name='dl_image',
            field=models.ImageField(blank='true', default='', null=True, upload_to='media/'),
        ),
    ]
