# Generated by Django 4.0.4 on 2022-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0017_alter_car_booking_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='card_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='card_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='exp_month',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='exp_year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
