# Generated by Django 4.0.4 on 2022-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentals', '0018_car_booking_card_name_car_booking_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_booking',
            old_name='card_number',
            new_name='card_num',
        ),
    ]
